name: "Verify Linked Issue"
description: "A GitHub action that verifies a pull request contains a reference to an issue."
branding:
  icon: check-square
  color: green
inputs:
  keyword:
    description: keyword that must present before the link
    default: ""
  keyword_link_not_required:
    description: keyword that means that the linkage is not required for this PR
  owner:
    description: owner of the repo, used in the link
    default: ""
  repo:
    description: repo, used in the link
    default: ""
  validate_links:
    description: Validate that the requested issues exist
    default: "false"
  message:
    description: The text to use as the PR comment for when for pull requests with no linked issues.
  filename:
    description: The name of the file to use as the comment template for pull requests with no linked issues.
runs:
  using: "node16"
  main: "src/index.js"
